version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Vercel CLI locally
          # command: npm install vercel
          command: pnpm add -D vercel
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Deploy to Vercel
          command: |
            pnpm install --no-frozen-lockfile
            # npx vercel --prod --token $VERCEL_TOKEN \
            #   --env NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY} \
            #   --env NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
            #   --yes --confirm
            pnpm vercel --prod --token $VERCEL_TOKEN \
              --env NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
              --env NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
              --yes            

workflows:
  deploy:
    jobs:
      - deploy
